FROM library/alpine:latest

ENV LANG=en_US.UTF-8
ENV TZ=Asia/Shanghai
ENV ROOT_PASSWORD=root

RUN apk --no-cache upgrade \
    && apk add --no-cache ca-certificates tzdata openssh \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && sed -ri s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config \
    && rm -rf /var/cache/apk/* /tmp/* /root/.cache/* \
    && ssh-keygen -A 
    
ADD ssh.sh /usr/local/bin/ssh.sh

EXPOSE 22/tcp

ENTRYPOINT ["/usr/local/bin/ssh.sh"]
