FROM library/debian:latest

ENV ROOT_PASSWORD=root
ENV HTTP_USER=sakuya
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV TZ=Asia/Shanghai

RUN set -ex \
    && apt-get update \
    && apt-get install -yqq openssh-server locales tzdata curl bash \
    squid3 nghttp2 apache2-utils \
    
    && locale-gen en_US.UTF-8 \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && echo "Asia/Shanghai" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    # ssh set 
    && sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config \
    # set password for ssh and nghttp
    && htpasswd -b -c /etc/squid/password ${HTTP_USER} ${ROOT_PASSWORD} \
    # set v2ray
    && curl -L -o /tmp/go.sh https://install.direct/go.sh \
    && chmod +x /tmp/go.sh \
    && /tmp/go.sh \
    # make clean
    && apt-get clean \
    && apt-get autoclean \
    && apt-get autoremove \
    #&& dpkg --list | grep "^rc" | cut -d " " -f 3 | xargs dpkg --purge \
    && rm -rf /tmp/* /root/.cache /var/lib/apt/lists/*

#COPY config file
COPY nghttpx.conf /etc/nghttpx/nghttpx.conf
COPY squid.conf /etc/squid/squid.conf
COPY v2rayconfig.json /etc/v2ray/config.json
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

#vmess
ENV VMESS_PORT=9999
ENV VMESS_ID=00000000-0000-0000-0000-000000000000
ENV VMESS_LEVEL=1
ENV VMESS_ALTERID=64

#kcp
ENV KCP_PORT_VMESS=9999
ENV KCP_MUT=1350
ENV KCP_TTI=50
ENV KCP_UPLINK=5
ENV KCP_DOWNLINK=20
ENV KCP_READBUFF=2
ENV KCP_WRITEBUFF=2

EXPOSE 20443/tcp
EXPOSE 20443/udp
EXPOSE 22/tcp
EXPOSE ${VMESS_PORT}/tcp
EXPOSE ${KCP_PORT_VMESS}/udp

ENTRYPOINT [ "bash", "/usr/bin/entrypoint.sh" ]
